
version: '3.9'

services:
  db:
    image: postgres:14beta2-alpine3.14
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_DB: authServer
    ports:
      - "5432:5432"
